[tox]
envlist = lint, typing, py39, py310, py311, py312, py313
requires =
    tox-uv

[testenv]
dependency_groups = dev
extras = cmd-line
commands =
    pytest --cov fulgurate test --cov-report term --cov-report xml:coverage.xml test/

[testenv:lint]
dependency_groups = dev
extras = cmd-line
commands =
    pylint src/fulgurate/
    pylint --rcfile test/pylintrc test/

[testenv:typing]
dependency_groups = dev
extras = cmd-line
commands =
    mypy --non-interactive --install-types --strict src/
